AQI_Prediction-main/AQI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls', namespace='predict'))
]

AQI_Prediction-main/predict/urls.py
from django.urls import path
from . import views

app_name = "predict"

urlpatterns = [

    path('', views.predict, name='prediction_page'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]


AQI_Prediction-main/predict/models.py
from django.db import models


class PredResults(models.Model):

    input1 = models.CharField(max_length=100)
    input2 = models.CharField(max_length=100)
    input3 = models.CharField(max_length=100)
    classification = models.CharField(max_length=100)


    def __str__(self):
        return self.classification

AQI_Prediction-main/predict/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults
import requests
import json

def predict(request):
    return render(request, 'predict.html')


def predict_chances(request):

    if request.POST.get('action') == 'post':

        input1 = (request.POST.get('input1'))
        input2 = (request.POST.get('input2'))
        input3 = (request.POST.get('input3'))

        base_url = "https://api.waqi.info"

        token = open('waqitoken.txt').read()

        name = input3
        r = requests.get(base_url + f"/feed/{name}/?token={token}")
        pollutants = ['pm25', 'pm10', 'o3']
        val = []
        for i in pollutants:
            val.append(r.json()['data']['forecast']['daily'][i][0]['avg'])
        # print(val)

        # pollutants_add = [10.063455, 31.214742, 0.862796]

        result = val
        model = pd.read_pickle('new_model_realtime.pickle')

        obs_val = [[], [], []]

        for index, j in enumerate(pollutants):
            for i in range(7):
                avg, date, max, min = (r.json()['data']['forecast']['daily'][j][i]['avg'],
                                       r.json()['data']['forecast']['daily'][j][i]['day'],
                                       r.json()['data']['forecast']['daily'][j][i]['max'],
                                       r.json()['data']['forecast']['daily'][j][i]['min'])
                obs_val[index].append([avg, max, min, date])

        temp_l = [[], [], [], [], [], [], []]
        for k in range(7):
            temp_l[k].append(obs_val[0][k][3])
            for m in range(0, 3):

                l = []
                for n in range(0, 3):
                    l.append(obs_val[n][k][m])
                calculate_aqi = model.predict([l])
                temp_l[k].append(round(calculate_aqi[0], 2))

        weekly_data = {'avg_val': [], 'Max': [], 'Min': [], 'Date_val': []}

        for i in temp_l:
            weekly_data['Date_val'].append(str(i[0]))
            weekly_data['avg_val'].append(str(i[1]))
            weekly_data['Max'].append(str(i[2]))
            weekly_data['Min'].append(str(i[3]))

        json_string = json.dumps(weekly_data)


        # Make prediction
        result1 = model.predict([result])

        classification = round(result1[0], 2)

        PredResults.objects.create(input1=input1, input2=input2, input3=input3,
                                   classification=classification)

        return JsonResponse({'result': classification, 'input1': input1,
                             'input2': input2, 'input3': input3, 'result1': classification, 'json_string': json_string },
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)


AQI_Prediction-main/templates/base.html
<!doctype html>
<html lang="en">

    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>AQI prediction</title>
    <script>
    var stateObject = {
    "Andhra Pradesh" : {
   "Rajahmundry" : ["Anand Kala Kshetram, Rajamahendravaram, India"],
   "Tirupati" : ["Tirumala-APPCB, Tirupati, India", ]
       },
       "Assam" : {
           "Guwahati" : ["Railway Colony, Guwahati, India"]
       },
       "Bihar" : {
          "Gaya" : ["Collectorate, Gaya, India"],
   "Muzaffarpur" : ["Muzaffarpur Collectorate, Muzaffarpur, India"],
   "Patna" : ["Muradpur, Patna, India", "DRM Office Danapur, Patna, India", "Govt. High School Shikarpur, Patna, India", "Rajbansi Nagar, Patna, India"]
       },
       "Chandigarh" : {
           "Chandigarh" : ["Sector-25, Chandigarh, India"]
       },
"Dadra and Nagar Haveli" : {
   "Silvassa" : ["Phase-1 GIDC, Vapi, India"]
},
"Delhi" : {
   "New Delhi" : ["New Delhi US Embassy, India"]
},
"Gujarat" :{
   "Ahmedabad" : ["Maninagar, Ahmedabad, India"],
   "Ankleshwar" : ["GIDC, Ankleshwar, India"],
   "Gandhinagar" : ["Sector-10, Gandhinagar, India"] },
"Haryana" : {
   "Faridabad": ["New Industrial Town, Faridabad, India", "Sector 11, Faridabad, India", "Sector16A Faridabad, Faridabad, India"],
   "Gurgaon" : ["Vikas Sadan Gurgaon, Gurgaon, India", "Vikas Sadan Gurgaon, Gurgaon"],
   "Ambala" : ["Patti Mehar, Ambala, India"],
   "Bhiwani" : ["H.B. Colony, Bhiwani, India"]
},
"Karnataka" : {
   "Bijapur" : ["Ibrahimpur, Vijayapura, India"],
   "Gulbarga" : ["Lal Bahadur Shastri Nagar, Kalaburagi, India"],
   "Hubli" : ["Deshpande Nagar, Hubballi, India"],
   "Mysore" : ["Hebbal 1st Stage, Mysuru, India"]
},
"Kerala" : {
   "Calicut" : ["Palayam, Kozhikode, India"],
   "Quilon" : ["Polayathode, Kollam, India"],
   "Thiruvananthapuram" : ["Plammoodu, Thiruvananthapuram, India", "Kariavattom, Thiruvananthapuram, India"]},
"Madhya Pradesh" : {
   "Bhopal" : ["T T Nagar, Bhopal, India"],
   "Gwalior" : ["Phool Bagh, Gwalior, India", "City Center, Gwalior, India"],
   "Indore" : ["Chhoti Gwaltoli, Indore, India"]
},
    "Maharashtra" : {
          "Mumbai" : ["Mahape, Navi Mumbai, India", "Colaba, Mumbai, India", "Borivali East, Mumbai, India", "Colaba, Mumbai, India", "Kurla, Mumbai, India", "Powai, Mumbai, India", "Sion, Mumbai, India", "Vasai West, Mumbai, India"],
          "Kalyan":["Khadakpada, Kalyan, India"],
       "Nagpur":["Opp GPO Civil Lines, Nagpur"],
       "Nasik":["Gangapur Road, Nashik, India"],
       "Pune":["Shivajinagar, Pune, Pune, India", "Alandi, Pune, Pune, India", "Bhumkar Chowk, Pune, Pune, India", "Hadapsar, Pune, Pune, India", "Katraj, Pune, Pune, India", "Lohegaon, Pune, Pune, India"],
       "Solapur": ["Solapur, Solapur, India"],
       },
"Meghalaya" : {
   "Shillong" : ["Lumpyngngad, Shillong, India"]
},
"Mizoram" : {
   "Aizawl" : ["Sikulpuikawn, Aizawl, India"]
},
"Punjab" : {
   "Amritsar" : ["Golden Temple, Amritsar, India"]
},
"Rajasthan" : {
   "Ajmer" : ["Civil Lines, Ajmer, India"],
   "Alwar" : ["Moti Doongri, Alwar, India"],
   "Jaipur" : ["Shastri Nagar, Jaipur, India", "Adarsh Nagar, Jaipur, India", "Police Commissionerate, Jaipur, India"],
   "Jodhpur" : ["Collectorate, Jodhpur, India"],
   "Kota": ["Shrinath Puram, Kota, India"]
},
"Tamil Nadu" : {
   "Chennai" : ["Chennai US Consulate, Chennai, India"]
},
"Uttar Pradesh" : {
   "Lucknow" : ["Lalbagh, West Lucknow, Lucknow"],
   "Noida" : ["Sector - 125, Noida, India"]
},

    }
    window.onload = function () {
    var input1 = document.getElementById("input1"),
    input2 = document.getElementById("input2"),
    input3 = document.getElementById("input3");
    for (var country in stateObject) {
    input1.options[input1.options.length] = new Option(country, country);
    }
    input1.onchange = function () {
    input2.length = 1; // remove all options bar first
    input3.length = 1; // remove all options bar first
    if (this.selectedIndex < 1) return; // done
    for (var state in stateObject[this.value]) {
    input2.options[input2.options.length] = new Option(state, state);
    }
    }
    input1.onchange(); // reset in case page is reloaded
    input2.onchange = function () {
    input3.length = 1; // remove all options bar first
    if (this.selectedIndex < 1) return; // done
    var district = stateObject[input1.value][this.value];
    for (var i = 0; i < district.length; i++) {
    input3.options[input3.options.length] = new Option(district[i], district[i]);
    }
    }
    }
    </script>
    <style>
      #intro {
        background-image: url("https://mdbootstrap.com/img/new/fluid/city/018.jpg");
        height: 100vh;
      }

      /* Height for devices larger than 576px */
      @media (min-width: 992px) {
        #intro {
          margin-top: -58.59px;
        }
      }

      .navbar .nav-link {
        color: #fff !important;
      }
    </style>
      <!-- Background image -->
    <!--<div id="intro" class="bg-image shadow-2-strong">
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
       <div class="container d-flex align-items-center justify-content-center text-center h-100">
          <div class="text-white">
            <h1 class="mb-3">Learn Bootstrap 5 with MDB</h1>
            <h5 class="mb-4">Best & free guide of responsive web design</h5>
            <a class="btn btn-outline-light btn-lg m-2" href="https://www.youtube.com/watch?v=c9B4TPnak1A" role="button"
              rel="nofollow" target="_blank">Start tutorial</a>
            <a class="btn btn-outline-light btn-lg m-2" href="https://mdbootstrap.com/docs/standard/" target="_blank"
              role="button">Download MDB UI KIT</a>
          </div>
        </div>
      </div>
    </div>-->
    <!-- Background image -->
    </head>
    <body id="intro">


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

AQI_Prediction-main/templates/predict.html
{% extends "index.html" %}

{% block main %}

<!-- Modal -->
<div>
    <p>
    </p>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
    <div class="container" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 bg-info">
                        <h5>Prediction Input:</h5>
                        <div>State: <span id="i1"></span></div>
                        <div>City: <span id="i2"></span></div>
                        <div>StationName: <span id="i3"></span></div>
                        <h5 class="pt-3">Prediction Classification:</h5>
                        <div>AQI Value: <span id="prediction"></span></div>
                    </div>
                    <div id="d" class="col-md-6 "><h5>weekly data:</h5> <span id="record"></span></div>
                </div>
            </div>
            <div id="myDIV"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>







<div class="container">
  <div class="row">
    <div class="col-md-6 bg-info">
      <h1>Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="input1">State</label>
                    <select class="form-control" size="1" id="input1" placeholder="" required>
                        <option value="" selected="selected">Please select State</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="input2">City</label>
                    <select class="form-control" size="1" id="input2" placeholder="" required>
                        <option value="" selected="selected">Please select City</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="input3">StationName</label>
                    <select class="form-control" size="1" id="input3" placeholder="" required>
                        <option value="" selected="selected">Please select Station</option>
                    </select>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
    </div>
    <div class="col-md-6 ">
        <h1 style="text-align: center; color: #FFCDD2">AQI Quality</h1>
      <svg width="400" height="110">
        <rect  x="30" y="-10" width="50" height="50" style="fill:yellow;"/>
          <rect  x="100" y="-10" width="500" height="50" style="fill:yellow;" />
            <text x="120" y="30" font-family="Verdana" font-size="20" >Moderate</text>
          <rect x="30" y="60" width="50" height="50" style="fill:orangered;"/>
            <rect  x="100" y="60" width="500" height="50" style="fill:orangered;" />
                <text x="100" y="100" font-family="Verdana" font-size="20" fill="black">Not good for sensitive groups</text></svg>
        <svg>
            <rect x="30" y="25" width="50" height="50" style="fill:green;"/>
            <rect  x="100" y="25" width="1000" height="50" style="fill:green;" />
                <text x=120 y="60" font-family="Verdana" font-size="20" fill="white">Good</text>
            <rect x="30" y="100" width="50" height="50" style="fill:red;"/>
                 <rect  x="100" y="100" width="500" height="50" style="fill:red;" />
                    <text x=120 y="130" font-family="Verdana" font-size="20" fill="white">Unhealthy</text></svg>
          <svg><rect x="30" y="25" width="50" height="50" style="fill:purple;"/>
              <rect  x="100" y="25" width="500" height="50" style="fill:purple;" />
              <text x=120 y="60" font-family="Verdana" font-size="20" fill="white">Very Unhealthy</text>
          <rect x="30" y="100" width="50" height="50" style="fill:maroon;"/>
              <rect  x="100" y="100" width="500" height="50" style="fill:maroon;" />
              <text x=120 y="130" font-family="Verdana" font-size="20" fill="white">Hazardous</text>
          </svg>
    </div>
  </div>
</div>
  </header>
<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                input1:$('#input1').val(),
                input2:$('#input2').val(),
                input3:$('#input3').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();

                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("i1").innerHTML = json['input1']
                document.getElementById("i2").innerHTML = json['input2']
                document.getElementById("i3").innerHTML = json['input3']
                document.getElementById("record").innerHTML = json['json_string']



                const json_val = json['json_string'];
                const obj = JSON.parse(json_val);
                obj.Date_val0 = new Date(obj.Date_val[0]);
                obj.Date_val1 = new Date(obj.Date_val[1]);
                obj.Date_val2 = new Date(obj.Date_val[2]);
                obj.Date_val3 = new Date(obj.Date_val[3]);
                obj.Date_val4 = new Date(obj.Date_val[4]);
                obj.Date_val5 = new Date(obj.Date_val[5]);
                obj.Date_val6 = new Date(obj.Date_val[6]);


                document.getElementById("d").innerHTML ="<html>\n" +
                    "<head>\n" +
                    "<style>\n" +
                    "table, th, td {\n" +
                    "  border: 1px solid black;\n" +
                    "  border-collapse: collapse;\n" +
                    "padding: 10px;"+
                    "}\n" +
                    "</style>\n" +
                    "</head>\n" +
                    "<body><table style=\"background-color:#FFCDD2;\">" +
                    "<tr><th colspan='4' style=\"vertical-align : middle;text-align:center;\" >Weekly Data</th></tr>"+
                    "<tr>\n" + "<th>Date</th>\n"+ "<th>Avg</th>\n"
                    +"<th>Max</th>\n" + "<th>Min</th>\n" + "  </tr>\n" +
                    " <tr>\n" + "<td>"+obj.Date_val0.getDate()+"-"+(obj.Date_val0.getMonth()+1)+"-"+obj.Date_val0.getFullYear()+"</td>\n"+"<td>"+obj.avg_val[0]+"</td>\n" +"<td>"+obj.Max[0]+"</td>\n"+"<td>"+obj.Min[0]+"</td>\n"+ " </tr>"+
                    " <tr>\n" + "<td>"+obj.Date_val1.getDate()+"-"+(obj.Date_val1.getMonth()+1)+"-"+obj.Date_val1.getFullYear()+"</td>\n"+"<td>"+obj.avg_val[1]+"</td>\n" +"<td>"+obj.Max[1]+"</td>\n"+"<td>"+obj.Min[1]+"</td>\n"+ " </tr>" +
                    " <tr>\n" + "<td>"+obj.Date_val2.getDate()+"-"+(obj.Date_val2.getMonth()+1)+"-"+obj.Date_val2.getFullYear()+"</td>\n"+"<td>"+obj.avg_val[2]+"</td>\n" +"<td>"+obj.Max[2]+"</td>\n"+"<td>"+obj.Min[2]+"</td>\n"+ " </tr>" +
                    " <tr>\n" + "<td>"+obj.Date_val3.getDate()+"-"+(obj.Date_val3.getMonth()+1)+"-"+obj.Date_val3.getFullYear()+"</td>\n"+"<td>"+obj.avg_val[3]+"</td>\n" +"<td>"+obj.Max[3]+"</td>\n"+"<td>"+obj.Min[3]+"</td>\n"+ " </tr>" +
                    " <tr>\n" + "<td>"+obj.Date_val4.getDate()+"-"+(obj.Date_val4.getMonth()+1)+"-"+obj.Date_val4.getFullYear()+"</td>\n"+"<td>"+obj.avg_val[4]+"</td>\n" +"<td>"+obj.Max[4]+"</td>\n"+"<td>"+obj.Min[4]+"</td>\n"+ " </tr>" +
                    " <tr>\n" + "<td>"+obj.Date_val5.getDate()+"-"+(obj.Date_val5.getMonth()+1)+"-"+obj.Date_val5.getFullYear()+"</td>\n"+"<td>"+obj.avg_val[5]+"</td>\n" +"<td>"+obj.Max[5]+"</td>\n"+"<td>"+obj.Min[5]+"</td>\n"+ " </tr>" +
                    " <tr>\n" + "<td>"+obj.Date_val6.getDate()+"-"+(obj.Date_val6.getMonth()+1)+"-"+obj.Date_val6.getFullYear()+"</td>\n"+"<td>"+obj.avg_val[6]+"</td>\n" +"<td>"+obj.Max[6]+"</td>\n"+"<td>"+obj.Min[6]+"</td>\n"+ " </tr>" +
                    "</table>";







                var time = json['result1']

                if (time < 51) {
                    document.getElementById("myDIV").style.backgroundColor = 'green';
                    document.getElementById("myDIV").style.color = 'white';
                    document.getElementById("myDIV").innerHTML = "<h3>Health Implications</h3>"+" : <br> " +
                        "Air quality is considered satisfactory, and air pollution poses little or no risk. \<br>" +
                        "Cautionary Statement (for PM2.5) : <br> None.";
                } else if (time > 50 && time < 101) {
                    document.getElementById("myDIV").style.backgroundColor = "yellow";
                    var str = "<h3>Health Implications</h3> : <br> " +
                        "Air quality is acceptable; however, for some pollutants there may be a moderate health " +
                        "concern for a very small number of people who are unusually sensitive to air pollution. <br>" +
                        "Cautionary Statement (for PM2.5) : <br> Active children and adults, and people with respiratory " +
                        "disease, such as asthma, should limit prolonged outdoor exertion.";
                    document.getElementById("myDIV").innerHTML = str;
                } else if (time > 100 && time < 151) {
                    document.getElementById("myDIV").style.backgroundColor = 'orange';
                    document.getElementById("myDIV").innerHTML = "<h3>Health Implications</h3>: <br> " +
                        "Members of sensitive groups may experience health effects. The general public is not likely to be affected. <br>" +
                        "Cautionary Statement (for PM2.5) : <br> Active children and adults, and people with respiratory disease, such as " +
                        "asthma, should limit prolonged outdoor exertion.";
                } else if (time > 150 && time < 201) {
                    document.getElementById("myDIV").style.backgroundColor = 'red';
                    document.getElementById("myDIV").style.color = 'white';
                    document.getElementById("myDIV").innerHTML = "<h3>Health Implications </h3>: <br> " +
                        "Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects. <br>" +
                        "Cautionary Statement (for PM2.5) : <br> Active children and adults, and people with respiratory disease, such as " +
                        "asthma, should avoid prolonged outdoor exertion; everyone else, especially children, should limit prolonged outdoor exertion.";
                } else if (time > 200 && time < 301) {
                    document.getElementById("myDIV").style.backgroundColor = 'purple';
                    document.getElementById("myDIV").style.color = 'white';
                    document.getElementById("myDIV").innerHTML="<h3>Health Implications</h3> : <br> " +
                        "Health warnings of emergency conditions. The entire population is more likely to be affected. <br>" +
                        "Cautionary Statement (for PM2.5) : <br> Active children and adults, and people with respiratory disease, such as asthma, " +
                        "should avoid all outdoor exertion; everyone else, especially children, should limit outdoor exertion. ";
                } else {
                    document.getElementById("myDIV").style.backgroundColor = 'maroon';
                    document.getElementById("myDIV").style.color = 'white';
                    document.getElementById("myDIV").innerHTML="<h3>Health Implications</h3> : <br> " +
                        "Health alert: everyone may experience more serious health effects. <br>" +
                        "Cautionary Statement (for PM2.5) : <br> Everyone should avoid all outdoor exertion. ";
                }
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

AQI_Prediction-main/templates/results.html
{% extends "index.html" %}

{% block main %}
    <div class="container pt-5 " >
        <div class="row">

        <h1 style="color: #FFFFFF">Prediction Results</h1>

            <table class="table" style="background-color: #FFCDD2">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">State</th>
                <th scope="col">City</th>
                <th scope="col">StationName</th>
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.input1 }}</td>
                    <td>{{ data.input2 }}</td>
                    <td>{{ data.input3 }}</td>
                    <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}